# Generated by Django 5.2.3 on 2025-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blog_options_blog_is_featured_blog_summary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequentlyAskedQuestion',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
