# Generated by Django 5.0 on 2025-01-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testimonial'),
        ('app', '0005_frequentlyaskedquestion'),
    ]

    operations = [
    ]
